GET http://localhost:5000/administration/newMatches
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI1OTc0ODEzfQ.PCTG9HPKAoTnGt6oKmcy9-A1CIoeIYOn2w061tTMPQ8
